/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <fcntl.h>
#include <unistd.h>
#include <math.h>
#include <string.h>
#include <sys/ioctl.h>
/* Header for class com_example_puyopuyo_GameSurfacer */

#ifndef _Included_com_example_puyopuyo_GameSurface
#define _Included_com_example_puyopuyo_GameSurface

#define LCD_MAGIC 0xBD
#define LCD_SET_CURSOR_POS  _IOW(LCD_MAGIC, 0, int)

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_puyopuyo_StageManager
 * Method:    ledWrite
 * Signature: (I)I
 */


JNIEXPORT jint JNICALL Java_com_example_puyopuyo_GameSurface_lcdWrite(JNIEnv * jenv, jobject self, jstring temp, jint pos){
    int fd;
    const char * text = (*jenv)->GetStringUTFChars(jenv, temp, NULL);
    fd = open("/dev/lcd", O_WRONLY);

    if(fd<0){
//__android_log_print(ANDROID_LOG_ERROR, "ledWrite", "Device open error : /dev/led\n");
        return -1;
    }

    ioctl(fd, LCD_SET_CURSOR_POS, &pos, _IOC_SIZE(LCD_SET_CURSOR_POS));
    write(fd, text, strlen(text));

    close(fd);
    return 0;

}

#ifdef __cplusplus
}
#endif
#endif