/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <fcntl.h>
#include <unistd.h>
#include <math.h>
/* Header for class com_example_puyopuyo_StageManager */

#ifndef _Included_com_example_puyopuyo_StageManager
#define _Included_com_example_puyopuyo_StageManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_puyopuyo_StageManager
 * Method:    ledWrite
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_puyopuyo_StageManager_ledWrite(JNIEnv * jenv, jobject self, jint combo){
    int fd;
    unsigned char bytedata;
    unsigned char ret;

    if((combo <0) | (combo > 0xff)){
        //__android_log_print(ANDROID_LOG_ERROR, "ledWrite", "Invalid range\n");
        return -1;
    }

    fd = open("/dev/led", O_RDWR);
    if(fd<0){
        //__android_log_print(ANDROID_LOG_ERROR, "ledWrite", "Device open error : /dev/led\n");
        return -1;
    }

    // 1combo : 1번 led On
    // 2combo : 2번 led On....

    if(combo >=8)
        combo = 8;

    bytedata = pow(2.0, combo) - 1;
    ret = write(fd, &bytedata, 1);
    if(ret <0){
        //__android_log_print(ANDROID_LOG_ERROR, "ledWrite", "Write Error\n");
        return -1;
    }

    close(fd);
    return 0;
}

#ifdef __cplusplus
}
#endif
#endif