/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <android/log.h>


#define NO_PUSH -1
#define LEFT 0
#define DOWN 1
#define RIGHT 2
#define ROTATE_LEFT 3
#define ROTATE_RIGHT 4
/* Header for class com_example_booyobooyo_MainActivity */

#ifndef _Included_com_example_puyopuyo_MainActivity
#define _Included_com_example_puyopuyo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_booyobooyo_MainActivity
 * Method:    pushBtnRead
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_puyopuyo_GameSurface_pushBtnRead(JNIEnv * jenv, jobject self){
    int fd;
    unsigned char bytedata;
    unsigned char ret;
    int key;
    fd = open("/dev/pushBtn", O_RDWR);

    if(fd < 0){
        //__android_log_print(ANDROID_LOG_ERROR, "pushBtnRead", "Device open error : /dev/pushBtn\n");
        return -1;
    }

    // 1: 0x01
    // 2: 0x02
    // 3: 0x04
    // 4: 0x08
    // 5: 0x10
    // 6: 0x20
    // 7: 0x40
    // 8: 0x80
    // 9: ?

    // 0x02: UP
    // 0x08: LEFT
    // 0x10: Down
    // 0x20 : Right
    ret = read(fd, &bytedata, 2);
    if(ret < 0){
        //__android_log_print(ANDROID_LOG_ERROR, "pushBtnRead", "read error\n");
    }


    switch(bytedata){
        case 0x00:
            key = NO_PUSH;
            break;
        case 0x02:
            key = ROTATE_LEFT;
            //__android_log_print(ANDROID_LOG_DEBUG, "pushBtnRead", "Current pushBtn value: %#d\n", key);
            break;
        case 0x04:
            key = ROTATE_RIGHT;
            break;
        case 0x08:
            key = LEFT;
            break;
        case 0x10:
            key = DOWN;
            break;
        case 0x20:
            key = RIGHT;
            break;
    }
    close(fd);
    return key;
}
#ifdef __cplusplus
}
#endif
#endif
